name: Build AArch64 GCC

on:
  push:
    branches:
      - main

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libgmp-dev libmpfr-dev libmpc-dev texinfo

      - name: Download GCC source code
        run: |
          wget https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz
          tar -xvf gcc-14.1.0.tar.xz
          

      - name: Configure and build GCC
        run: |
         cd ./gcc-14.1.0
          mkdir build
          cd build
          ../configure --target=aarch64-linux-gnu --host=x86_64-linux-gnu --build=x86_64-linux-gnu --prefix=/data/data/com.vectras.boxvidra/files/usr/glibc --disable-multilib --enable-languages=c,c++,fortran --disable-bootstrap \
                --disable-nls \
                --enable-default-pie \
                --with-system-zlib \
                --enable-__cxa_atexit \
                --enable-linker-build-id \
                --enable-plugin \
                --with-linker-hash-style=gnu \
                --enable-gnu-indirect-function \
                --disable-werror \
                --disable-checking \
                --disable-static \                                                --enable-host-shared \
                --disable-libssp \
                --disable-libstdcxx-pch \
          make -j4
          make install

      - name: Package GCC
        run: |
          cd /data/data/com.vectras.boxvidra/files/usr/glibc
          tar -czvf gcc-aarch64.tar.gz .

      - name: Upload GCC package
        uses: actions/upload-artifact@v3
        with:
          name: gcc-aarch64
          path: /data/data/com.vectras.boxvidra/files/usr/glibc/gcc-aarch64.tar.gz
