name: Build AArch64 GCC

on:
  push:
    branches:
      - main

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build AArch64 GCC
        run: |
          docker run --rm -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -t gcc-aarch64-image /bin/bash -c "docker build -t gcc-aarch64-image ."
